name: anime_list
description: Lists the main animes that will be released and the ones from the current season.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.0
  dio: ^4.0.0
  flash: ^2.0.1
  hooks_riverpod: ^1.0.0-dev.5
  riverpod: ^1.0.0-dev.5
  flutter_riverpod: ^1.0.0-dev.5
  material_design_icons_flutter: ^5.0.5955-rc.1
  flutter_hooks: ^0.18.0
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0  
  build_runner: ^2.1.2
  freezed: ^0.14.2
  lint: ^1.5.3
  mocktail: ^0.1.4
  faker: ^2.0.0
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  fonts:
  - family: Urbanist
    fonts:
    - asset: assets/fonts/Urbanist-Light.ttf
      weight: 300
    - asset: assets/fonts/Urbanist-Regular.ttf
      weight: 400
    - asset: assets/fonts/Urbanist-Medium.ttf
      weight: 500
    - asset: assets/fonts/Urbanist-SemiBold.ttf
      weight: 600
